const comment = {
    subreddit_id: 't5_2qh0u',
    approved_at_utc: null,
    ups: 466,
    mod_reason_by: null,
    banned_by: null,
    author_flair_type: 'text',
    removal_reason: null,
    link_id: 't3_9mg2y8',
    author_flair_template_id: null,
    likes: null,
    no_follow: false,
    replies: {
      kind: 'Listing',
      data: {
        modhash: '',
        dist: null,
        children: [
          {
            kind: 't1',
            data: {
              subreddit_id: 't5_2qh0u',
              approved_at_utc: null,
              ups: 66,
              mod_reason_by: null,
              banned_by: null,
              author_flair_type: 'text',
              removal_reason: null,
              link_id: 't3_9mg2y8',
              author_flair_template_id: null,
              likes: null,
              no_follow: false,
              replies: {
                kind: 'Listing',
                data: {
                  modhash: '',
                  dist: null,
                  children: [
                    {
                      kind: 't1',
                      data: {
                        subreddit_id: 't5_2qh0u',
                        approved_at_utc: null,
                        ups: 102,
                        mod_reason_by: null,
                        banned_by: null,
                        author_flair_type: 'text',
                        removal_reason: null,
                        link_id: 't3_9mg2y8',
                        author_flair_template_id: null,
                        likes: null,
                        no_follow: false,
                        replies: {
                          kind: 'Listing',
                          data: {
                            modhash: '',
                            dist: null,
                            children: [
                              {
                                kind: 't1',
                                data: {
                                  subreddit_id: 't5_2qh0u',
                                  approved_at_utc: null,
                                  ups: 23,
                                  mod_reason_by: null,
                                  banned_by: null,
                                  author_flair_type: 'text',
                                  removal_reason: null,
                                  link_id: 't3_9mg2y8',
                                  author_flair_template_id: null,
                                  likes: null,
                                  no_follow: false,
                                  replies: {
                                    kind: 'Listing',
                                    data: {
                                      modhash: '',
                                      dist: null,
                                      children: [
                                        {
                                          kind: 't1',
                                          data: {
                                            subreddit_id: 't5_2qh0u',
                                            approved_at_utc: null,
                                            ups: 32,
                                            mod_reason_by: null,
                                            banned_by: null,
                                            author_flair_type: 'text',
                                            removal_reason: null,
                                            link_id: 't3_9mg2y8',
                                            author_flair_template_id: null,
                                            likes: null,
                                            no_follow: false,
                                            replies: {
                                              kind: 'Listing',
                                              data: {
                                                modhash: '',
                                                dist: null,
                                                children: [
                                                  {
                                                    kind: 't1',
                                                    data: {
                                                      subreddit_id: 't5_2qh0u',
                                                      approved_at_utc: null,
                                                      ups: 16,
                                                      mod_reason_by: null,
                                                      banned_by: null,
                                                      author_flair_type: 'text',
                                                      removal_reason: null,
                                                      link_id: 't3_9mg2y8',
                                                      author_flair_template_id: null,
                                                      likes: null,
                                                      no_follow: false,
                                                      replies: {
                                                        kind: 'Listing',
                                                        data: {
                                                          modhash: '',
                                                          dist: null,
                                                          children: [
                                                            {
                                                              kind: 't1',
                                                              data: {
                                                                subreddit_id: 't5_2qh0u',
                                                                approved_at_utc: null,
                                                                ups: 12,
                                                                mod_reason_by: null,
                                                                banned_by: null,
                                                                author_flair_type: 'text',
                                                                removal_reason: null,
                                                                link_id: 't3_9mg2y8',
                                                                author_flair_template_id: null,
                                                                likes: null,
                                                                no_follow: false,
                                                                replies: '',
                                                                user_reports: [],
                                                                saved: false,
                                                                id: 'e7g3hzx',
                                                                banned_at_utc: null,
                                                                mod_reason_title: null,
                                                                gilded: 0,
                                                                archived: false,
                                                                report_reasons: null,
                                                                author: 'BasedOnAir',
                                                                can_mod_post: false,
                                                                send_replies: true,
                                                                parent_id: 't1_e7emunt',
                                                                score: 12,
                                                                author_fullname: 't2_11eas5',
                                                                approved_by: null,
                                                                downs: 0,
                                                                body: 'Thanks for the information that\'s very interesting to learn and I appreciate the openness about it',
                                                                edited: false,
                                                                author_flair_css_class: null,
                                                                is_submitter: false,
                                                                collapsed: false,
                                                                author_flair_richtext: [],
                                                                author_patreon_flair: false,
                                                                collapsed_reason: null,
                                                                body_html: '&lt;div class="md"&gt;&lt;p&gt;Thanks for the information that&amp;#39;s very interesting to learn and I appreciate the openness about it&lt;/p&gt;\n&lt;/div&gt;',
                                                                stickied: false,
                                                                subreddit_type: 'public',
                                                                can_gild: true,
                                                                gildings: {
                                                                  gid_1: 0,
                                                                  gid_2: 0,
                                                                  gid_3: 0
                                                                },
                                                                author_flair_text_color: null,
                                                                score_hidden: false,
                                                                permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e7g3hzx/',
                                                                num_reports: null,
                                                                name: 't1_e7g3hzx',
                                                                created: 1539115865,
                                                                subreddit: 'pics',
                                                                author_flair_text: null,
                                                                created_utc: 1539087065,
                                                                subreddit_name_prefixed: 'r/pics',
                                                                controversiality: 0,
                                                                depth: 6,
                                                                author_flair_background_color: null,
                                                                mod_reports: [],
                                                                mod_note: null,
                                                                distinguished: null
                                                              }
                                                            }
                                                          ],
                                                          after: null,
                                                          before: null
                                                        }
                                                      },
                                                      user_reports: [],
                                                      saved: false,
                                                      id: 'e7emunt',
                                                      banned_at_utc: null,
                                                      mod_reason_title: null,
                                                      gilded: 0,
                                                      archived: false,
                                                      report_reasons: null,
                                                      author: 'n_reineke',
                                                      can_mod_post: false,
                                                      send_replies: true,
                                                      parent_id: 't1_e7elobu',
                                                      score: 16,
                                                      author_fullname: 't2_7qmzk',
                                                      approved_by: null,
                                                      downs: 0,
                                                      body: 'To a degree that is something that\'s been considered. But, think about historically relevant or other interesting photos that may otherwise seem benign?\n\nAlso, you agree you have common sense and that you\'d implement it right, but could you get 20 strangers to pull/approve everything with 100% accuracy on your suggestion alone?\n\n\nIt would be a highly subjective rule at the will of whichever mod decides if a photo is good enough to "stand alone".  \n\nWhen all is over, we hope that titles are direct, relatively short, and only include information relative to the content at hand (which sometimes does include cancer).',
                                                      edited: 1539026836,
                                                      author_flair_css_class: null,
                                                      is_submitter: true,
                                                      collapsed: false,
                                                      author_flair_richtext: [],
                                                      author_patreon_flair: false,
                                                      collapsed_reason: null,
                                                      body_html: '&lt;div class="md"&gt;&lt;p&gt;To a degree that is something that&amp;#39;s been considered. But, think about historically relevant or other interesting photos that may otherwise seem benign?&lt;/p&gt;\n\n&lt;p&gt;Also, you agree you have common sense and that you&amp;#39;d implement it right, but could you get 20 strangers to pull/approve everything with 100% accuracy on your suggestion alone?&lt;/p&gt;\n\n&lt;p&gt;It would be a highly subjective rule at the will of whichever mod decides if a photo is good enough to &amp;quot;stand alone&amp;quot;.  &lt;/p&gt;\n\n&lt;p&gt;When all is over, we hope that titles are direct, relatively short, and only include information relative to the content at hand (which sometimes does include cancer).&lt;/p&gt;\n&lt;/div&gt;',
                                                      stickied: false,
                                                      subreddit_type: 'public',
                                                      can_gild: true,
                                                      gildings: {
                                                        gid_1: 0,
                                                        gid_2: 0,
                                                        gid_3: 0
                                                      },
                                                      author_flair_text_color: 'dark',
                                                      score_hidden: false,
                                                      permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e7emunt/',
                                                      num_reports: null,
                                                      name: 't1_e7emunt',
                                                      created: 1539052545,
                                                      subreddit: 'pics',
                                                      author_flair_text: 'Outkast',
                                                      created_utc: 1539023745,
                                                      subreddit_name_prefixed: 'r/pics',
                                                      controversiality: 0,
                                                      depth: 5,
                                                      author_flair_background_color: '',
                                                      mod_reports: [],
                                                      mod_note: null,
                                                      distinguished: null
                                                    }
                                                  },
                                                  {
                                                    kind: 't1',
                                                    data: {
                                                      subreddit_id: 't5_2qh0u',
                                                      approved_at_utc: null,
                                                      ups: 1,
                                                      mod_reason_by: null,
                                                      banned_by: null,
                                                      author_flair_type: 'text',
                                                      removal_reason: null,
                                                      link_id: 't3_9mg2y8',
                                                      author_flair_template_id: null,
                                                      likes: null,
                                                      no_follow: true,
                                                      replies: '',
                                                      user_reports: [],
                                                      saved: false,
                                                      id: 'e8ca5iz',
                                                      banned_at_utc: null,
                                                      mod_reason_title: null,
                                                      gilded: 0,
                                                      archived: false,
                                                      report_reasons: null,
                                                      author: 'peterthefatman',
                                                      can_mod_post: false,
                                                      send_replies: true,
                                                      parent_id: 't1_e7elobu',
                                                      score: 1,
                                                      author_fullname: 't2_6i478vp',
                                                      approved_by: null,
                                                      downs: 0,
                                                      body: 'I totally get where you\'re coming from and I had the same mindset too. But that was until someone replied to my comment a while back. What about the top all time pic of the woman on the plane? Without the tittle we\'d have never known her feat and what she did. I\'m now in an I don\'t know area. Some context is good but I do agree that the tittle shouldn\'t make the pic. Mods if you could do something that allows "backstory posts" but aren\'t ones clearly designed to fish for upvotes like the heroin ones than that\'d be a good step. ',
                                                      edited: false,
                                                      author_flair_css_class: null,
                                                      is_submitter: false,
                                                      collapsed: false,
                                                      author_flair_richtext: [],
                                                      author_patreon_flair: false,
                                                      collapsed_reason: null,
                                                      body_html: '&lt;div class="md"&gt;&lt;p&gt;I totally get where you&amp;#39;re coming from and I had the same mindset too. But that was until someone replied to my comment a while back. What about the top all time pic of the woman on the plane? Without the tittle we&amp;#39;d have never known her feat and what she did. I&amp;#39;m now in an I don&amp;#39;t know area. Some context is good but I do agree that the tittle shouldn&amp;#39;t make the pic. Mods if you could do something that allows &amp;quot;backstory posts&amp;quot; but aren&amp;#39;t ones clearly designed to fish for upvotes like the heroin ones than that&amp;#39;d be a good step. &lt;/p&gt;\n&lt;/div&gt;',
                                                      stickied: false,
                                                      subreddit_type: 'public',
                                                      can_gild: true,
                                                      gildings: {
                                                        gid_1: 0,
                                                        gid_2: 0,
                                                        gid_3: 0
                                                      },
                                                      author_flair_text_color: null,
                                                      score_hidden: false,
                                                      permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e8ca5iz/',
                                                      num_reports: null,
                                                      name: 't1_e8ca5iz',
                                                      created: 1540381788,
                                                      subreddit: 'pics',
                                                      author_flair_text: null,
                                                      created_utc: 1540352988,
                                                      subreddit_name_prefixed: 'r/pics',
                                                      controversiality: 0,
                                                      depth: 5,
                                                      author_flair_background_color: null,
                                                      mod_reports: [],
                                                      mod_note: null,
                                                      distinguished: null
                                                    }
                                                  },
                                                  {
                                                    kind: 't1',
                                                    data: {
                                                      subreddit_id: 't5_2qh0u',
                                                      approved_at_utc: null,
                                                      ups: 1,
                                                      mod_reason_by: null,
                                                      banned_by: null,
                                                      removal_reason: null,
                                                      link_id: 't3_9mg2y8',
                                                      author_flair_template_id: null,
                                                      likes: null,
                                                      no_follow: true,
                                                      replies: {
                                                        kind: 'Listing',
                                                        data: {
                                                          modhash: '',
                                                          dist: null,
                                                          children: [
                                                            {
                                                              kind: 't1',
                                                              data: {
                                                                subreddit_id: 't5_2qh0u',
                                                                approved_at_utc: null,
                                                                ups: 2,
                                                                mod_reason_by: null,
                                                                banned_by: null,
                                                                author_flair_type: 'text',
                                                                removal_reason: null,
                                                                link_id: 't3_9mg2y8',
                                                                author_flair_template_id: null,
                                                                likes: null,
                                                                no_follow: true,
                                                                replies: '',
                                                                user_reports: [],
                                                                saved: false,
                                                                id: 'e9n8749',
                                                                banned_at_utc: null,
                                                                mod_reason_title: null,
                                                                gilded: 0,
                                                                archived: false,
                                                                report_reasons: null,
                                                                author: 'J_M',
                                                                can_mod_post: false,
                                                                send_replies: true,
                                                                parent_id: 't1_e9n5g38',
                                                                score: 2,
                                                                author_fullname: 't2_4kqdx',
                                                                approved_by: null,
                                                                downs: 0,
                                                                body: 'Subbed, thanks.\n\nEdit: Loving rule #2',
                                                                edited: false,
                                                                author_flair_css_class: null,
                                                                is_submitter: false,
                                                                collapsed: false,
                                                                author_flair_richtext: [],
                                                                author_patreon_flair: false,
                                                                collapsed_reason: null,
                                                                body_html: '&lt;div class="md"&gt;&lt;p&gt;Subbed, thanks.&lt;/p&gt;\n\n&lt;p&gt;Edit: Loving rule #2&lt;/p&gt;\n&lt;/div&gt;',
                                                                stickied: false,
                                                                subreddit_type: 'public',
                                                                can_gild: true,
                                                                gildings: {
                                                                  gid_1: 0,
                                                                  gid_2: 0,
                                                                  gid_3: 0
                                                                },
                                                                author_flair_text_color: null,
                                                                score_hidden: false,
                                                                permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e9n8749/',
                                                                num_reports: null,
                                                                name: 't1_e9n8749',
                                                                created: 1542176615,
                                                                subreddit: 'pics',
                                                                author_flair_text: null,
                                                                created_utc: 1542147815,
                                                                subreddit_name_prefixed: 'r/pics',
                                                                controversiality: 0,
                                                                depth: 6,
                                                                author_flair_background_color: null,
                                                                mod_reports: [],
                                                                mod_note: null,
                                                                distinguished: null
                                                              }
                                                            }
                                                          ],
                                                          after: null,
                                                          before: null
                                                        }
                                                      },
                                                      user_reports: [],
                                                      saved: false,
                                                      id: 'e9n5g38',
                                                      banned_at_utc: null,
                                                      mod_reason_title: null,
                                                      gilded: 0,
                                                      archived: false,
                                                      report_reasons: null,
                                                      author: '[deleted]',
                                                      can_mod_post: false,
                                                      send_replies: true,
                                                      parent_id: 't1_e7elobu',
                                                      score: 1,
                                                      approved_by: null,
                                                      downs: 0,
                                                      body: '[removed]',
                                                      edited: false,
                                                      author_flair_css_class: null,
                                                      collapsed: true,
                                                      is_submitter: false,
                                                      collapsed_reason: null,
                                                      body_html: '&lt;div class="md"&gt;&lt;p&gt;[removed]&lt;/p&gt;\n&lt;/div&gt;',
                                                      stickied: false,
                                                      subreddit_type: 'public',
                                                      can_gild: true,
                                                      gildings: {
                                                        gid_1: 0,
                                                        gid_2: 0,
                                                        gid_3: 0
                                                      },
                                                      author_flair_text_color: 'dark',
                                                      score_hidden: false,
                                                      permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e9n5g38/',
                                                      num_reports: null,
                                                      name: 't1_e9n5g38',
                                                      created: 1542174366,
                                                      subreddit: 'pics',
                                                      author_flair_text: null,
                                                      created_utc: 1542145566,
                                                      subreddit_name_prefixed: 'r/pics',
                                                      controversiality: 0,
                                                      depth: 5,
                                                      author_flair_background_color: '',
                                                      mod_reports: [],
                                                      mod_note: null,
                                                      distinguished: null
                                                    }
                                                  }
                                                ],
                                                after: null,
                                                before: null
                                              }
                                            },
                                            user_reports: [],
                                            saved: false,
                                            id: 'e7elobu',
                                            banned_at_utc: null,
                                            mod_reason_title: null,
                                            gilded: 0,
                                            archived: false,
                                            report_reasons: null,
                                            author: 'J_M',
                                            can_mod_post: false,
                                            send_replies: true,
                                            parent_id: 't1_e7ekfgn',
                                            score: 32,
                                            author_fullname: 't2_4kqdx',
                                            approved_by: null,
                                            downs: 0,
                                            body: 'Thank you for the insight into your process, I appreciate it.\n\nPerhaps the simplest way to prove content, speaking for myself only of course, would be to ask yourself "Does this pic stand alone? Does it require the title to explain/justify it?" If it isn\'t visually interesting enough to stand on its own without a backstory it probably isn\'t a good pic.',
                                            edited: false,
                                            author_flair_css_class: null,
                                            is_submitter: false,
                                            collapsed: false,
                                            author_flair_richtext: [],
                                            author_patreon_flair: false,
                                            collapsed_reason: null,
                                            body_html: '&lt;div class="md"&gt;&lt;p&gt;Thank you for the insight into your process, I appreciate it.&lt;/p&gt;\n\n&lt;p&gt;Perhaps the simplest way to prove content, speaking for myself only of course, would be to ask yourself &amp;quot;Does this pic stand alone? Does it require the title to explain/justify it?&amp;quot; If it isn&amp;#39;t visually interesting enough to stand on its own without a backstory it probably isn&amp;#39;t a good pic.&lt;/p&gt;\n&lt;/div&gt;',
                                            stickied: false,
                                            subreddit_type: 'public',
                                            can_gild: true,
                                            gildings: {
                                              gid_1: 0,
                                              gid_2: 0,
                                              gid_3: 0
                                            },
                                            author_flair_text_color: null,
                                            score_hidden: false,
                                            permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e7elobu/',
                                            num_reports: null,
                                            name: 't1_e7elobu',
                                            created: 1539051561,
                                            subreddit: 'pics',
                                            author_flair_text: null,
                                            created_utc: 1539022761,
                                            subreddit_name_prefixed: 'r/pics',
                                            controversiality: 0,
                                            depth: 4,
                                            author_flair_background_color: null,
                                            mod_reports: [],
                                            mod_note: null,
                                            distinguished: null
                                          }
                                        },
                                        {
                                          kind: 't1',
                                          data: {
                                            subreddit_id: 't5_2qh0u',
                                            approved_at_utc: null,
                                            ups: 17,
                                            mod_reason_by: null,
                                            banned_by: null,
                                            removal_reason: null,
                                            link_id: 't3_9mg2y8',
                                            author_flair_template_id: null,
                                            likes: null,
                                            no_follow: true,
                                            replies: {
                                              kind: 'Listing',
                                              data: {
                                                modhash: '',
                                                dist: null,
                                                children: [
                                                  {
                                                    kind: 't1',
                                                    data: {
                                                      subreddit_id: 't5_2qh0u',
                                                      approved_at_utc: null,
                                                      ups: 8,
                                                      mod_reason_by: null,
                                                      banned_by: null,
                                                      author_flair_type: 'text',
                                                      removal_reason: null,
                                                      link_id: 't3_9mg2y8',
                                                      author_flair_template_id: null,
                                                      likes: null,
                                                      no_follow: false,
                                                      replies: {
                                                        kind: 'Listing',
                                                        data: {
                                                          modhash: '',
                                                          dist: null,
                                                          children: [
                                                            {
                                                              kind: 't1',
                                                              data: {
                                                                subreddit_id: 't5_2qh0u',
                                                                approved_at_utc: null,
                                                                ups: 1,
                                                                mod_reason_by: null,
                                                                banned_by: null,
                                                                author_flair_type: 'text',
                                                                removal_reason: null,
                                                                link_id: 't3_9mg2y8',
                                                                author_flair_template_id: null,
                                                                likes: null,
                                                                no_follow: true,
                                                                replies: '',
                                                                user_reports: [],
                                                                saved: false,
                                                                id: 'e7wy5ri',
                                                                banned_at_utc: null,
                                                                mod_reason_title: null,
                                                                gilded: 0,
                                                                archived: false,
                                                                report_reasons: null,
                                                                author: 'rawrhissmeow',
                                                                can_mod_post: false,
                                                                send_replies: true,
                                                                parent_id: 't1_e7g3esp',
                                                                score: 1,
                                                                author_fullname: 't2_w9tbs',
                                                                approved_by: null,
                                                                downs: 0,
                                                                body: 'No idea why you would get downvoted for a well thought out response....thank you for all you do!',
                                                                edited: false,
                                                                author_flair_css_class: null,
                                                                is_submitter: false,
                                                                collapsed: false,
                                                                author_flair_richtext: [],
                                                                author_patreon_flair: false,
                                                                collapsed_reason: null,
                                                                body_html: '&lt;div class="md"&gt;&lt;p&gt;No idea why you would get downvoted for a well thought out response....thank you for all you do!&lt;/p&gt;\n&lt;/div&gt;',
                                                                stickied: false,
                                                                subreddit_type: 'public',
                                                                can_gild: true,
                                                                gildings: {
                                                                  gid_1: 0,
                                                                  gid_2: 0,
                                                                  gid_3: 0
                                                                },
                                                                author_flair_text_color: null,
                                                                score_hidden: false,
                                                                permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e7wy5ri/',
                                                                num_reports: null,
                                                                name: 't1_e7wy5ri',
                                                                created: 1539775687,
                                                                subreddit: 'pics',
                                                                author_flair_text: null,
                                                                created_utc: 1539746887,
                                                                subreddit_name_prefixed: 'r/pics',
                                                                controversiality: 0,
                                                                depth: 6,
                                                                author_flair_background_color: null,
                                                                mod_reports: [],
                                                                mod_note: null,
                                                                distinguished: null
                                                              }
                                                            }
                                                          ],
                                                          after: null,
                                                          before: null
                                                        }
                                                      },
                                                      user_reports: [],
                                                      saved: false,
                                                      id: 'e7g3esp',
                                                      banned_at_utc: null,
                                                      mod_reason_title: null,
                                                      gilded: 0,
                                                      archived: false,
                                                      report_reasons: null,
                                                      author: 'n_reineke',
                                                      can_mod_post: false,
                                                      send_replies: true,
                                                      parent_id: 't1_e7fxbl1',
                                                      score: 8,
                                                      author_fullname: 't2_7qmzk',
                                                      approved_by: null,
                                                      downs: 0,
                                                      body: '1. We\'re not going to pull photos for their content unless it breaks rules 1-3.  Just because the subject of a photo may be a "sympathetic" topic doesn\'t mean anything as long as the title is relevant.\n\n2. We do not allow begging in this sub, and ban for it outright, so I\'m not sure where you\'re getting this from.\n\n3. Your callous choice of words kinda drives my point, that the rule is subjective and depends on the person\'s opinions on the matter, which is why we are working towards rules that can be understood and implemented across the mod team effectively.',
                                                      edited: false,
                                                      author_flair_css_class: null,
                                                      is_submitter: true,
                                                      collapsed: false,
                                                      author_flair_richtext: [],
                                                      author_patreon_flair: false,
                                                      collapsed_reason: null,
                                                      body_html: '&lt;div class="md"&gt;&lt;ol&gt;\n&lt;li&gt;&lt;p&gt;We&amp;#39;re not going to pull photos for their content unless it breaks rules 1-3.  Just because the subject of a photo may be a &amp;quot;sympathetic&amp;quot; topic doesn&amp;#39;t mean anything as long as the title is relevant.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;We do not allow begging in this sub, and ban for it outright, so I&amp;#39;m not sure where you&amp;#39;re getting this from.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Your callous choice of words kinda drives my point, that the rule is subjective and depends on the person&amp;#39;s opinions on the matter, which is why we are working towards rules that can be understood and implemented across the mod team effectively.&lt;/p&gt;&lt;/li&gt;\n&lt;/ol&gt;\n&lt;/div&gt;',
                                                      stickied: false,
                                                      subreddit_type: 'public',
                                                      can_gild: true,
                                                      gildings: {
                                                        gid_1: 0,
                                                        gid_2: 0,
                                                        gid_3: 0
                                                      },
                                                      author_flair_text_color: 'dark',
                                                      score_hidden: false,
                                                      permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e7g3esp/',
                                                      num_reports: null,
                                                      name: 't1_e7g3esp',
                                                      created: 1539115746,
                                                      subreddit: 'pics',
                                                      author_flair_text: 'Outkast',
                                                      created_utc: 1539086946,
                                                      subreddit_name_prefixed: 'r/pics',
                                                      controversiality: 1,
                                                      depth: 5,
                                                      author_flair_background_color: '',
                                                      mod_reports: [],
                                                      mod_note: null,
                                                      distinguished: null
                                                    }
                                                  }
                                                ],
                                                after: null,
                                                before: null
                                              }
                                            },
                                            user_reports: [],
                                            saved: false,
                                            id: 'e7fxbl1',
                                            banned_at_utc: null,
                                            mod_reason_title: null,
                                            gilded: 0,
                                            archived: false,
                                            report_reasons: null,
                                            author: '[deleted]',
                                            can_mod_post: false,
                                            send_replies: true,
                                            parent_id: 't1_e7ekfgn',
                                            score: 17,
                                            approved_by: null,
                                            downs: 0,
                                            body: '[deleted]',
                                            edited: false,
                                            author_flair_css_class: null,
                                            collapsed: true,
                                            is_submitter: false,
                                            collapsed_reason: null,
                                            body_html: '&lt;div class="md"&gt;&lt;p&gt;[deleted]&lt;/p&gt;\n&lt;/div&gt;',
                                            stickied: false,
                                            subreddit_type: 'public',
                                            can_gild: true,
                                            gildings: {
                                              gid_1: 0,
                                              gid_2: 0,
                                              gid_3: 0
                                            },
                                            author_flair_text_color: 'dark',
                                            score_hidden: false,
                                            permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e7fxbl1/',
                                            num_reports: null,
                                            name: 't1_e7fxbl1',
                                            created: 1539104678,
                                            subreddit: 'pics',
                                            author_flair_text: null,
                                            created_utc: 1539075878,
                                            subreddit_name_prefixed: 'r/pics',
                                            controversiality: 0,
                                            depth: 4,
                                            author_flair_background_color: '',
                                            mod_reports: [],
                                            mod_note: null,
                                            distinguished: null
                                          }
                                        }
                                      ],
                                      after: null,
                                      before: null
                                    }
                                  },
                                  user_reports: [],
                                  saved: false,
                                  id: 'e7ekfgn',
                                  banned_at_utc: null,
                                  mod_reason_title: null,
                                  gilded: 0,
                                  archived: false,
                                  report_reasons: null,
                                  author: 'n_reineke',
                                  can_mod_post: false,
                                  send_replies: true,
                                  parent_id: 't1_e7ejksx',
                                  score: 23,
                                  author_fullname: 't2_7qmzk',
                                  approved_by: null,
                                  downs: 0,
                                  body: 'We had inconsistency in the past when rules were made, how many mods were actually around when it was implemented, and what the intent of the language driving it was.\n\nThe "sympathy" rule was a quick &amp; dirty fix for a more complex issue with a discussion that was never fully had. \n\nAs a result, we often discuss case by case when something is on the front page, and try not to step on the toes of whichever mod approved/pulled it until we\'re in the same page.\n\nThere are also times when we\'re just not around and something manages to get up there before we can act.\n\nWe have been working on parts of Rule 4 for a while now, and have the more complex discussion in our cross hairs.\n\nIt\'s not coming tomorrow, or even this week, but we are hoping to reach a consensus soon on how posts should be titled in the sub.',
                                  edited: false,
                                  author_flair_css_class: null,
                                  is_submitter: true,
                                  collapsed: false,
                                  author_flair_richtext: [],
                                  author_patreon_flair: false,
                                  collapsed_reason: null,
                                  body_html: '&lt;div class="md"&gt;&lt;p&gt;We had inconsistency in the past when rules were made, how many mods were actually around when it was implemented, and what the intent of the language driving it was.&lt;/p&gt;\n\n&lt;p&gt;The &amp;quot;sympathy&amp;quot; rule was a quick &amp;amp; dirty fix for a more complex issue with a discussion that was never fully had. &lt;/p&gt;\n\n&lt;p&gt;As a result, we often discuss case by case when something is on the front page, and try not to step on the toes of whichever mod approved/pulled it until we&amp;#39;re in the same page.&lt;/p&gt;\n\n&lt;p&gt;There are also times when we&amp;#39;re just not around and something manages to get up there before we can act.&lt;/p&gt;\n\n&lt;p&gt;We have been working on parts of Rule 4 for a while now, and have the more complex discussion in our cross hairs.&lt;/p&gt;\n\n&lt;p&gt;It&amp;#39;s not coming tomorrow, or even this week, but we are hoping to reach a consensus soon on how posts should be titled in the sub.&lt;/p&gt;\n&lt;/div&gt;',
                                  stickied: false,
                                  subreddit_type: 'public',
                                  can_gild: true,
                                  gildings: {
                                    gid_1: 0,
                                    gid_2: 0,
                                    gid_3: 0
                                  },
                                  author_flair_text_color: 'dark',
                                  score_hidden: false,
                                  permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e7ekfgn/',
                                  num_reports: null,
                                  name: 't1_e7ekfgn',
                                  created: 1539050511,
                                  subreddit: 'pics',
                                  author_flair_text: 'Outkast',
                                  created_utc: 1539021711,
                                  subreddit_name_prefixed: 'r/pics',
                                  controversiality: 0,
                                  depth: 3,
                                  author_flair_background_color: '',
                                  mod_reports: [],
                                  mod_note: null,
                                  distinguished: null
                                }
                              },
                              {
                                kind: 't1',
                                data: {
                                  subreddit_id: 't5_2qh0u',
                                  approved_at_utc: null,
                                  ups: 2,
                                  mod_reason_by: null,
                                  banned_by: null,
                                  author_flair_type: 'text',
                                  removal_reason: null,
                                  link_id: 't3_9mg2y8',
                                  author_flair_template_id: null,
                                  likes: null,
                                  no_follow: true,
                                  replies: '',
                                  user_reports: [],
                                  saved: false,
                                  id: 'e8v3ewo',
                                  banned_at_utc: null,
                                  mod_reason_title: null,
                                  gilded: 0,
                                  archived: false,
                                  report_reasons: null,
                                  author: 'EffrumScufflegrit',
                                  can_mod_post: false,
                                  send_replies: true,
                                  parent_id: 't1_e7ejksx',
                                  score: 2,
                                  author_fullname: 't2_92e86',
                                  approved_by: null,
                                  downs: 0,
                                  body: 'Im on a mod team where we get this complaint a lot and I\'ll say the same thing here. Use the report button. 9/10 we get a "why didn\'t you guys remove this?!" it doesn\'t have a single report on it and we just never saw it ',
                                  edited: false,
                                  author_flair_css_class: null,
                                  is_submitter: false,
                                  collapsed: false,
                                  author_flair_richtext: [],
                                  author_patreon_flair: false,
                                  collapsed_reason: null,
                                  body_html: '&lt;div class="md"&gt;&lt;p&gt;Im on a mod team where we get this complaint a lot and I&amp;#39;ll say the same thing here. Use the report button. 9/10 we get a &amp;quot;why didn&amp;#39;t you guys remove this?!&amp;quot; it doesn&amp;#39;t have a single report on it and we just never saw it &lt;/p&gt;\n&lt;/div&gt;',
                                  stickied: false,
                                  subreddit_type: 'public',
                                  can_gild: true,
                                  gildings: {
                                    gid_1: 0,
                                    gid_2: 0,
                                    gid_3: 0
                                  },
                                  author_flair_text_color: null,
                                  score_hidden: false,
                                  permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e8v3ewo/',
                                  num_reports: null,
                                  name: 't1_e8v3ewo',
                                  created: 1541125614,
                                  subreddit: 'pics',
                                  author_flair_text: null,
                                  created_utc: 1541096814,
                                  subreddit_name_prefixed: 'r/pics',
                                  controversiality: 0,
                                  depth: 3,
                                  author_flair_background_color: null,
                                  mod_reports: [],
                                  mod_note: null,
                                  distinguished: null
                                }
                              }
                            ],
                            after: null,
                            before: null
                          }
                        },
                        user_reports: [],
                        saved: false,
                        id: 'e7ejksx',
                        banned_at_utc: null,
                        mod_reason_title: null,
                        gilded: 0,
                        archived: false,
                        report_reasons: null,
                        author: 'J_M',
                        can_mod_post: false,
                        send_replies: true,
                        parent_id: 't1_e7egu35',
                        score: 102,
                        author_fullname: 't2_4kqdx',
                        approved_by: null,
                        downs: 0,
                        body: 'I understand it can be difficult but at the same time, clear cut blatant violations of the rules that would be perfect examples of rule violations are posted daily. Spammers selling jewelry might be a little harder to police but when a pic has no meaning without its title it should be in another sub.\n\nEdit: I do want to thank the mod team for the what they do - I know it\'s a lot of thankless work.',
                        edited: false,
                        author_flair_css_class: null,
                        is_submitter: false,
                        collapsed: false,
                        author_flair_richtext: [],
                        author_patreon_flair: false,
                        collapsed_reason: null,
                        body_html: '&lt;div class="md"&gt;&lt;p&gt;I understand it can be difficult but at the same time, clear cut blatant violations of the rules that would be perfect examples of rule violations are posted daily. Spammers selling jewelry might be a little harder to police but when a pic has no meaning without its title it should be in another sub.&lt;/p&gt;\n\n&lt;p&gt;Edit: I do want to thank the mod team for the what they do - I know it&amp;#39;s a lot of thankless work.&lt;/p&gt;\n&lt;/div&gt;',
                        stickied: false,
                        subreddit_type: 'public',
                        can_gild: true,
                        gildings: {
                          gid_1: 0,
                          gid_2: 0,
                          gid_3: 0
                        },
                        author_flair_text_color: null,
                        score_hidden: false,
                        permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e7ejksx/',
                        num_reports: null,
                        name: 't1_e7ejksx',
                        created: 1539049808,
                        subreddit: 'pics',
                        author_flair_text: null,
                        created_utc: 1539021008,
                        subreddit_name_prefixed: 'r/pics',
                        controversiality: 0,
                        depth: 2,
                        author_flair_background_color: null,
                        mod_reports: [],
                        mod_note: null,
                        distinguished: null
                      }
                    },
                    {
                      kind: 't1',
                      data: {
                        subreddit_id: 't5_2qh0u',
                        approved_at_utc: null,
                        ups: 2,
                        mod_reason_by: null,
                        banned_by: null,
                        author_flair_type: 'text',
                        removal_reason: null,
                        link_id: 't3_9mg2y8',
                        author_flair_template_id: null,
                        likes: null,
                        no_follow: true,
                        replies: '',
                        user_reports: [],
                        saved: false,
                        id: 'e8tsgmt',
                        banned_at_utc: null,
                        mod_reason_title: null,
                        gilded: 0,
                        archived: false,
                        report_reasons: null,
                        author: 'thefray777',
                        can_mod_post: false,
                        send_replies: true,
                        parent_id: 't1_e7egu35',
                        score: 2,
                        author_fullname: 't2_7sapg',
                        approved_by: null,
                        downs: 0,
                        body: 'Perhaps the rules could restrict post titles so that they must describe what\'s in the photo, but not a whole life story behind it. This would avoid the "I\'ve suffered" and the "i woke up at 5 am to take this" post titles. When there\'s interesting and relevant story behind a photo, the OP could post it in the comments.',
                        edited: false,
                        author_flair_css_class: null,
                        is_submitter: false,
                        collapsed: false,
                        author_flair_richtext: [],
                        author_patreon_flair: false,
                        collapsed_reason: null,
                        body_html: '&lt;div class="md"&gt;&lt;p&gt;Perhaps the rules could restrict post titles so that they must describe what&amp;#39;s in the photo, but not a whole life story behind it. This would avoid the &amp;quot;I&amp;#39;ve suffered&amp;quot; and the &amp;quot;i woke up at 5 am to take this&amp;quot; post titles. When there&amp;#39;s interesting and relevant story behind a photo, the OP could post it in the comments.&lt;/p&gt;\n&lt;/div&gt;',
                        stickied: false,
                        subreddit_type: 'public',
                        can_gild: true,
                        gildings: {
                          gid_1: 0,
                          gid_2: 0,
                          gid_3: 0
                        },
                        author_flair_text_color: null,
                        score_hidden: false,
                        permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e8tsgmt/',
                        num_reports: null,
                        name: 't1_e8tsgmt',
                        created: 1541067366,
                        subreddit: 'pics',
                        author_flair_text: null,
                        created_utc: 1541038566,
                        subreddit_name_prefixed: 'r/pics',
                        controversiality: 0,
                        depth: 2,
                        author_flair_background_color: null,
                        mod_reports: [],
                        mod_note: null,
                        distinguished: null
                      }
                    },
                    {
                      kind: 't1',
                      data: {
                        subreddit_id: 't5_2qh0u',
                        approved_at_utc: null,
                        ups: 1,
                        mod_reason_by: null,
                        banned_by: null,
                        author_flair_type: 'text',
                        removal_reason: null,
                        link_id: 't3_9mg2y8',
                        author_flair_template_id: null,
                        likes: null,
                        no_follow: true,
                        replies: '',
                        user_reports: [],
                        saved: false,
                        id: 'e8ixxw1',
                        banned_at_utc: null,
                        mod_reason_title: null,
                        gilded: 0,
                        archived: false,
                        report_reasons: null,
                        author: '51isnotprime',
                        can_mod_post: false,
                        send_replies: true,
                        parent_id: 't1_e7egu35',
                        score: 1,
                        author_fullname: 't2_lbtdq',
                        approved_by: null,
                        downs: 0,
                        body: 'AKA nothing is going to happen bc karma',
                        edited: false,
                        author_flair_css_class: null,
                        is_submitter: false,
                        collapsed: false,
                        author_flair_richtext: [],
                        author_patreon_flair: false,
                        collapsed_reason: null,
                        body_html: '&lt;div class="md"&gt;&lt;p&gt;AKA nothing is going to happen bc karma&lt;/p&gt;\n&lt;/div&gt;',
                        stickied: false,
                        subreddit_type: 'public',
                        can_gild: true,
                        gildings: {
                          gid_1: 0,
                          gid_2: 0,
                          gid_3: 0
                        },
                        author_flair_text_color: null,
                        score_hidden: false,
                        permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e8ixxw1/',
                        num_reports: null,
                        name: 't1_e8ixxw1',
                        created: 1540634342,
                        subreddit: 'pics',
                        author_flair_text: null,
                        created_utc: 1540605542,
                        subreddit_name_prefixed: 'r/pics',
                        controversiality: 0,
                        depth: 2,
                        author_flair_background_color: null,
                        mod_reports: [],
                        mod_note: null,
                        distinguished: null
                      }
                    }
                  ],
                  after: null,
                  before: null
                }
              },
              user_reports: [],
              saved: false,
              id: 'e7egu35',
              banned_at_utc: null,
              mod_reason_title: null,
              gilded: 0,
              archived: false,
              report_reasons: null,
              author: 'n_reineke',
              can_mod_post: false,
              send_replies: true,
              parent_id: 't1_e7eggdn',
              score: 66,
              author_fullname: 't2_7qmzk',
              approved_by: null,
              downs: 0,
              body: '&gt;For the past several months, the moderation team has been deliberating over how the subreddit\'s rules should evolve. \n\n&gt;As with similar processes – we didn\'t want to act with anything approaching rashness. Even so, we have heard our subscribers\' concerns\n\nSubjective rules are the most difficult to enforce evenly on a mod team.  \n\n\nWe are discussing all issues as we revamp  our rules, and how they should be phrased &amp; drawn out in the wiki to be clear to both users &amp; mod members.',
              edited: 1539020362,
              author_flair_css_class: null,
              is_submitter: true,
              collapsed: false,
              author_flair_richtext: [],
              author_patreon_flair: false,
              collapsed_reason: null,
              body_html: '&lt;div class="md"&gt;&lt;blockquote&gt;\n&lt;p&gt;For the past several months, the moderation team has been deliberating over how the subreddit&amp;#39;s rules should evolve. &lt;/p&gt;\n\n&lt;p&gt;As with similar processes – we didn&amp;#39;t want to act with anything approaching rashness. Even so, we have heard our subscribers&amp;#39; concerns&lt;/p&gt;\n&lt;/blockquote&gt;\n\n&lt;p&gt;Subjective rules are the most difficult to enforce evenly on a mod team.  &lt;/p&gt;\n\n&lt;p&gt;We are discussing all issues as we revamp  our rules, and how they should be phrased &amp;amp; drawn out in the wiki to be clear to both users &amp;amp; mod members.&lt;/p&gt;\n&lt;/div&gt;',
              stickied: false,
              subreddit_type: 'public',
              can_gild: true,
              gildings: {
                gid_1: 0,
                gid_2: 0,
                gid_3: 0
              },
              author_flair_text_color: 'dark',
              score_hidden: false,
              permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e7egu35/',
              num_reports: null,
              name: 't1_e7egu35',
              created: 1539047547,
              subreddit: 'pics',
              author_flair_text: 'Outkast',
              created_utc: 1539018747,
              subreddit_name_prefixed: 'r/pics',
              controversiality: 0,
              depth: 1,
              author_flair_background_color: '',
              mod_reports: [],
              mod_note: null,
              distinguished: null
            }
          }
        ],
        after: null,
        before: null
      }
    },
    user_reports: [],
    saved: false,
    id: 'e7eggdn',
    banned_at_utc: null,
    mod_reason_title: null,
    gilded: 0,
    archived: false,
    report_reasons: null,
    author: 'J_M',
    can_mod_post: false,
    send_replies: true,
    parent_id: 't3_9mg2y8',
    score: 466,
    author_fullname: 't2_4kqdx',
    approved_by: null,
    downs: 0,
    body: 'Now how about enforcing the existing title rules a bit? \n\n&gt; 6 must not be "designed to elicit sympathy"\n\nI quit heroin, beating my dog, being depressed, eating junk food...here\'s a selfie or a meaningless picture of nothing in particular so I can gather attaboys in r/pics.',
    edited: 1539018633,
    author_flair_css_class: null,
    is_submitter: false,
    collapsed: false,
    author_flair_richtext: [],
    author_patreon_flair: false,
    collapsed_reason: null,
    body_html: '&lt;div class="md"&gt;&lt;p&gt;Now how about enforcing the existing title rules a bit? &lt;/p&gt;\n\n&lt;blockquote&gt;\n&lt;p&gt;6 must not be &amp;quot;designed to elicit sympathy&amp;quot;&lt;/p&gt;\n&lt;/blockquote&gt;\n\n&lt;p&gt;I quit heroin, beating my dog, being depressed, eating junk food...here&amp;#39;s a selfie or a meaningless picture of nothing in particular so I can gather attaboys in &lt;a href="/r/pics"&gt;r/pics&lt;/a&gt;.&lt;/p&gt;\n&lt;/div&gt;',
    stickied: false,
    subreddit_type: 'public',
    can_gild: true,
    gildings: {
      gid_1: 0,
      gid_2: 0,
      gid_3: 0
    },
    author_flair_text_color: null,
    score_hidden: false,
    permalink: '/r/pics/comments/9mg2y8/hello_it_appears_that_this_post_is_a_progress/e7eggdn/',
    num_reports: null,
    name: 't1_e7eggdn',
    created: 1539047226,
    subreddit: 'pics',
    author_flair_text: null,
    created_utc: 1539018426,
    subreddit_name_prefixed: 'r/pics',
    controversiality: 0,
    depth: 0,
    author_flair_background_color: null,
    mod_reports: [],
    mod_note: null,
    distinguished: null
};

export default comment;
